### PR TITLE
Add Canary to Versions:

### PR DESCRIPTION
**Pull request by shirshak55**

### CODE REVIEW

**Review by ueokande — CHANGES_REQUESTED** [review]
I tried it with [`edge-version: canary`](https://github.com/browser-actions/setup-edge/compare/install-with-canary?expand=1), but not works.  Canary does not exists on [product api](https://edgeupdates.microsoft.com/api/products?view=enterprise).

Do you have any idea to install canary edge?

**Comment by shirshak55** [comment]
Strange is Canary called "EdgeUpdate". I really don't understand why they don't even clearly mention canary link.

**Comment by ueokande** [comment]
The downloaded binary from EdgeUpdate says:
> Unknown Installer Error

It may be for an Edge Update Service and not a standalone installer

**Comment by ueokande** [comment]
@shirshak55 
Canary is now supported on #2.  Thank you for your request

**Pull request closed without merging**
